version: '3'


services:

  app:
    build: .
#    ports:
#      - '8080:8080'
    volumes:
#      - .:/app
      - ./src/:/app/src/
      - ./entry.sh/:/app/entry.sh
      - maven-repo:/root/.m2/

    depends_on:
      - postgres
    networks:
      - internal
#    environment:
#      - DB_HOST: postgres
  postgres:
    image: postgres
    networks:
      - internal


volumes:
  maven-repo:

networks:
  internal:
    driver: bridge


