version: '3'


services:

  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
#      - .:/app
      - maven-repo:/usr/share/maven/lib

    depends_on:
      - postgres

#    environment:
#      - DB_HOST: postgres
  postgres:
    image: postgres


volumes:
  maven-repo:

